import streamlit as st
from prometheus_client import generate_latest


def show_metrics():
    """
    Display Prometheus metrics in the Streamlit UI.
    """

    st.title("Observability")

    st.write(
        """
        This page exposes Prometheus metrics generated by the platform.

        These metrics include:

        - course scan counts
        - scan duration histograms
        - scan failures
        - API errors
        """
    )

    st.divider()

    st.subheader("Prometheus Metrics")

    metrics_data = generate_latest().decode("utf-8")

    st.code(metrics_data, language="text")